BEGIN TRANSACTION;
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS001','Python Programming',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS002','Data Structures',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS003','Database Systems',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS004','Web Development',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS005','Software Engineering',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS006','Computer Networks',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS007','Cyber Security',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS008','Operating Systems',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS009','AI Fundamentals',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS010','Cloud Computing',3.0,1,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS011','Engineering Mechanics',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS012','Thermodynamics',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS013','Machine Design',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS014','Fluid Mechanics',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS015','CAD Design',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS016','Manufacturing Systems',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS017','Materials Engineering',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS018','Robotics',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS019','Industrial Engineering',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS020','Control Systems',3.0,2,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS021','Financial Accounting',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS022','Marketing Management',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS023','Business Analytics',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS024','Human Resource Management',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS025','Economics',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS026','Entrepreneurship',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS027','Operations Management',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS028','Business Law',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS029','Strategic Management',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS030','Digital Marketing',3.0,3,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS031','Calculus',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS032','Linear Algebra',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS033','Statistics',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS034','Discrete Mathematics',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS035','Numerical Methods',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS036','Probability',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS037','Differential Equations',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS038','Optimization',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS039','Mathematical Modeling',3.0,4,'Undergraduate');
INSERT INTO Courses(CourseCode,CourseName,Credits,DepartmentID,CourseLevel) VALUES ('CRS040','Applied Mathematics',3.0,4,'Undergraduate');
COMMIT;
